trigger:
  branches:
    include:
    - refs/heads/main #define the branch that will be used
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main #define the branch that will be used

stages:
- stage: deployArtifact
  variables: 
    - group: <name-variable-group> #define the group variable to be used
  jobs:
  - job: deployArtifactJob
    displayName: deployArtifactJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      fetchDepth: 1
    - task: AzureKeyVault@2
      displayName: Azure Key Vault
      inputs:
        azureSubscription: '$(AZURE_SUBSCRIPTION)'
        KeyVaultName: '$(KEY_VAULT_NAME)'
        SecretsFilter: '*'
    - task: qetza.replacetokens.replacetokens-task.replacetokens@5
      displayName: Replace tokens in *.yml
      inputs:
        rootDirectory: bundle
        targetFiles: '*.yml'
        tokenPattern: custom
        tokenPrefix: ___ 
        tokenSuffix: ___
    - task: UsePythonVersion@0
      displayName: Use Python 3.11
      inputs:
        versionSpec: 3.11
    - task: PowerShell@2
      displayName: install libs
      inputs:
        targetType: inline
        script: >-
          python -m pip install --upgrade pip

          python -m pip install ruamel.yaml
    - task: PythonScript@0
      name: ''
      displayName: Replace yml Workflows
      inputs:
        scriptPath: bundle/replace_wkf.py
        arguments: '--adb_secret $(ADB_SECRET)'
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: bundle
        ArtifactName: wkf

